/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Rarity = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'rare' : IDL.Null,
  'common' : IDL.Null,
});
export const Bundle = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'rarity' : Rarity,
});
export const Sensitivity = IDL.Record({
  'id' : IDL.Nat,
  'gyroscope' : IDL.Nat,
  'deviceLabel' : IDL.Text,
  'scope2x' : IDL.Nat,
  'scope4x' : IDL.Nat,
  'awmScope' : IDL.Nat,
  'general' : IDL.Nat,
  'redDot' : IDL.Nat,
});
export const Category = IDL.Variant({
  'movement' : IDL.Null,
  'technique' : IDL.Null,
  'settings' : IDL.Null,
});
export const HeadshotTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'description' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addBundle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Rarity], [Bundle], []),
  'addSensitivity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [Sensitivity],
      [],
    ),
  'addTip' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Nat],
      [HeadshotTip],
      [],
    ),
  'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteBundle' : IDL.Func([IDL.Nat], [], []),
  'deleteSensitivity' : IDL.Func([IDL.Nat], [], []),
  'deleteTip' : IDL.Func([IDL.Nat], [], []),
  'getBundle' : IDL.Func([IDL.Nat], [Bundle], ['query']),
  'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
  'getSensitivities' : IDL.Func([], [IDL.Vec(Sensitivity)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'sensitivityCount' : IDL.Nat,
          'tipCount' : IDL.Nat,
          'bundleCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTips' : IDL.Func([], [IDL.Vec(HeadshotTip)], ['query']),
  'updateBundle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Rarity],
      [Bundle],
      [],
    ),
  'updateSensitivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [Sensitivity],
      [],
    ),
  'updateTip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Category, IDL.Nat],
      [HeadshotTip],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Rarity = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'rare' : IDL.Null,
    'common' : IDL.Null,
  });
  const Bundle = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'rarity' : Rarity,
  });
  const Sensitivity = IDL.Record({
    'id' : IDL.Nat,
    'gyroscope' : IDL.Nat,
    'deviceLabel' : IDL.Text,
    'scope2x' : IDL.Nat,
    'scope4x' : IDL.Nat,
    'awmScope' : IDL.Nat,
    'general' : IDL.Nat,
    'redDot' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'movement' : IDL.Null,
    'technique' : IDL.Null,
    'settings' : IDL.Null,
  });
  const HeadshotTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'description' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'addBundle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Rarity],
        [Bundle],
        [],
      ),
    'addSensitivity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [Sensitivity],
        [],
      ),
    'addTip' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Nat],
        [HeadshotTip],
        [],
      ),
    'checkAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteBundle' : IDL.Func([IDL.Nat], [], []),
    'deleteSensitivity' : IDL.Func([IDL.Nat], [], []),
    'deleteTip' : IDL.Func([IDL.Nat], [], []),
    'getBundle' : IDL.Func([IDL.Nat], [Bundle], ['query']),
    'getBundles' : IDL.Func([], [IDL.Vec(Bundle)], ['query']),
    'getSensitivities' : IDL.Func([], [IDL.Vec(Sensitivity)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'sensitivityCount' : IDL.Nat,
            'tipCount' : IDL.Nat,
            'bundleCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTips' : IDL.Func([], [IDL.Vec(HeadshotTip)], ['query']),
    'updateBundle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Rarity],
        [Bundle],
        [],
      ),
    'updateSensitivity' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [Sensitivity],
        [],
      ),
    'updateTip' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Category, IDL.Nat],
        [HeadshotTip],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };