/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bundle {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'rarity' : Rarity,
}
export type Category = { 'movement' : null } |
  { 'technique' : null } |
  { 'settings' : null };
export interface HeadshotTip {
  'id' : bigint,
  'title' : string,
  'displayOrder' : bigint,
  'description' : string,
  'category' : Category,
}
export type Rarity = { 'epic' : null } |
  { 'legendary' : null } |
  { 'rare' : null } |
  { 'common' : null };
export interface Sensitivity {
  'id' : bigint,
  'gyroscope' : bigint,
  'deviceLabel' : string,
  'scope2x' : bigint,
  'scope4x' : bigint,
  'awmScope' : bigint,
  'general' : bigint,
  'redDot' : bigint,
}
export interface _SERVICE {
  'addBundle' : ActorMethod<[string, string, string, Rarity], Bundle>,
  'addSensitivity' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, bigint],
    Sensitivity
  >,
  'addTip' : ActorMethod<[string, string, Category, bigint], HeadshotTip>,
  'checkAdminPassword' : ActorMethod<[string], boolean>,
  'deleteBundle' : ActorMethod<[bigint], undefined>,
  'deleteSensitivity' : ActorMethod<[bigint], undefined>,
  'deleteTip' : ActorMethod<[bigint], undefined>,
  'getBundle' : ActorMethod<[bigint], Bundle>,
  'getBundles' : ActorMethod<[], Array<Bundle>>,
  'getSensitivities' : ActorMethod<[], Array<Sensitivity>>,
  'getStats' : ActorMethod<
    [],
    { 'sensitivityCount' : bigint, 'tipCount' : bigint, 'bundleCount' : bigint }
  >,
  'getTips' : ActorMethod<[], Array<HeadshotTip>>,
  'updateBundle' : ActorMethod<
    [bigint, string, string, string, Rarity],
    Bundle
  >,
  'updateSensitivity' : ActorMethod<
    [bigint, string, bigint, bigint, bigint, bigint, bigint, bigint],
    Sensitivity
  >,
  'updateTip' : ActorMethod<
    [bigint, string, string, Category, bigint],
    HeadshotTip
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];