/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Bundle {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    rarity: Rarity;
}
export interface Sensitivity {
    id: bigint;
    gyroscope: bigint;
    deviceLabel: string;
    scope2x: bigint;
    scope4x: bigint;
    awmScope: bigint;
    general: bigint;
    redDot: bigint;
}
export interface HeadshotTip {
    id: bigint;
    title: string;
    displayOrder: bigint;
    description: string;
    category: Category;
}
export enum Category {
    movement = "movement",
    technique = "technique",
    settings = "settings"
}
export enum Rarity {
    epic = "epic",
    legendary = "legendary",
    rare = "rare",
    common = "common"
}
export interface backendInterface {
    addBundle(name: string, description: string, imageUrl: string, rarity: Rarity): Promise<Bundle>;
    addSensitivity(deviceLabel: string, general: bigint, redDot: bigint, scope2x: bigint, scope4x: bigint, awmScope: bigint, gyroscope: bigint): Promise<Sensitivity>;
    addTip(title: string, description: string, category: Category, displayOrder: bigint): Promise<HeadshotTip>;
    checkAdminPassword(password: string): Promise<boolean>;
    deleteBundle(id: bigint): Promise<void>;
    deleteSensitivity(id: bigint): Promise<void>;
    deleteTip(id: bigint): Promise<void>;
    getBundle(id: bigint): Promise<Bundle>;
    getBundles(): Promise<Array<Bundle>>;
    getSensitivities(): Promise<Array<Sensitivity>>;
    getStats(): Promise<{
        sensitivityCount: bigint;
        tipCount: bigint;
        bundleCount: bigint;
    }>;
    getTips(): Promise<Array<HeadshotTip>>;
    updateBundle(id: bigint, name: string, description: string, imageUrl: string, rarity: Rarity): Promise<Bundle>;
    updateSensitivity(id: bigint, deviceLabel: string, general: bigint, redDot: bigint, scope2x: bigint, scope4x: bigint, awmScope: bigint, gyroscope: bigint): Promise<Sensitivity>;
    updateTip(id: bigint, title: string, description: string, category: Category, displayOrder: bigint): Promise<HeadshotTip>;
}
import type { Bundle as _Bundle, Category as _Category, HeadshotTip as _HeadshotTip, Rarity as _Rarity } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBundle(arg0: string, arg1: string, arg2: string, arg3: Rarity): Promise<Bundle> {
        if (this.processError) {
            try {
                const result = await this.actor.addBundle(arg0, arg1, arg2, to_candid_Rarity_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBundle(arg0, arg1, arg2, to_candid_Rarity_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSensitivity(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<Sensitivity> {
        if (this.processError) {
            try {
                const result = await this.actor.addSensitivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSensitivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addTip(arg0: string, arg1: string, arg2: Category, arg3: bigint): Promise<HeadshotTip> {
        if (this.processError) {
            try {
                const result = await this.actor.addTip(arg0, arg1, to_candid_Category_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_HeadshotTip_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTip(arg0, arg1, to_candid_Category_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_HeadshotTip_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdminPassword(arg0);
            return result;
        }
    }
    async deleteBundle(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBundle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBundle(arg0);
            return result;
        }
    }
    async deleteSensitivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSensitivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSensitivity(arg0);
            return result;
        }
    }
    async deleteTip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTip(arg0);
            return result;
        }
    }
    async getBundle(arg0: bigint): Promise<Bundle> {
        if (this.processError) {
            try {
                const result = await this.actor.getBundle(arg0);
                return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBundle(arg0);
            return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBundles(): Promise<Array<Bundle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBundles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBundles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensitivities(): Promise<Array<Sensitivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensitivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensitivities();
            return result;
        }
    }
    async getStats(): Promise<{
        sensitivityCount: bigint;
        tipCount: bigint;
        bundleCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getTips(): Promise<Array<HeadshotTip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTips();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTips();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBundle(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Rarity): Promise<Bundle> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBundle(arg0, arg1, arg2, arg3, to_candid_Rarity_n1(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBundle(arg0, arg1, arg2, arg3, to_candid_Rarity_n1(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Bundle_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSensitivity(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<Sensitivity> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSensitivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSensitivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateTip(arg0: bigint, arg1: string, arg2: string, arg3: Category, arg4: bigint): Promise<HeadshotTip> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTip(arg0, arg1, arg2, to_candid_Category_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_HeadshotTip_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTip(arg0, arg1, arg2, to_candid_Category_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_HeadshotTip_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Bundle_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bundle): Bundle {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_HeadshotTip_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeadshotTip): HeadshotTip {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Rarity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rarity): Rarity {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    displayOrder: bigint;
    description: string;
    category: _Category;
}): {
    id: bigint;
    title: string;
    displayOrder: bigint;
    description: string;
    category: Category;
} {
    return {
        id: value.id,
        title: value.title,
        displayOrder: value.displayOrder,
        description: value.description,
        category: from_candid_Category_n11(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    rarity: _Rarity;
}): {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    rarity: Rarity;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        rarity: from_candid_Rarity_n5(_uploadFile, _downloadFile, value.rarity)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    movement: null;
} | {
    technique: null;
} | {
    settings: null;
}): Category {
    return "movement" in value ? Category.movement : "technique" in value ? Category.technique : "settings" in value ? Category.settings : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    epic: null;
} | {
    legendary: null;
} | {
    rare: null;
} | {
    common: null;
}): Rarity {
    return "epic" in value ? Rarity.epic : "legendary" in value ? Rarity.legendary : "rare" in value ? Rarity.rare : "common" in value ? Rarity.common : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bundle>): Array<Bundle> {
    return value.map((x)=>from_candid_Bundle_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HeadshotTip>): Array<HeadshotTip> {
    return value.map((x)=>from_candid_HeadshotTip_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Rarity_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rarity): _Rarity {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rarity): {
    epic: null;
} | {
    legendary: null;
} | {
    rare: null;
} | {
    common: null;
} {
    return value == Rarity.epic ? {
        epic: null
    } : value == Rarity.legendary ? {
        legendary: null
    } : value == Rarity.rare ? {
        rare: null
    } : value == Rarity.common ? {
        common: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    movement: null;
} | {
    technique: null;
} | {
    settings: null;
} {
    return value == Category.movement ? {
        movement: null
    } : value == Category.technique ? {
        technique: null
    } : value == Category.settings ? {
        settings: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
